# Generated by Django 4.0.6 on 2022-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='solde',
            field=models.IntegerField(default=0),
        ),
    ]
