# Generated by Django 4.0.6 on 2022-07-14 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_remove_compte_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='id',
        ),
        migrations.AddField(
            model_name='operation',
            name='compte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='compte.compte'),
        ),
        migrations.AddField(
            model_name='operation',
            name='idOpe',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
